Add aws secrets pre-run and template scripts - ready to work with aws-cli

diff --git a/scripts/templates/template-awssecrets b/scripts/templates/template-awssecrets
--- a/scripts/templates/template-awssecrets
+++ b/scripts/templates/template-awssecrets
@@ -17,10 +17,8 @@
 # <daemon-user:Daemon User:www-data:inline>
 # <daemon-group:Daemon Group:www-data:inline>
 # <script-user:Script User:root:inline>
-# <ssh-public-key:SSH Public Key:null:paste>
-# <ssh-private-key:SSH Private Key:null:paste>
-# <devops-public-key:Devops Public Key:null:paste:conditional=USING_DEVOPS_REPO>
-# <devops-private-key:Devops Private Key:null:paste:conditional=USING_DEVOPS_REPO>
+# <aws-region:AWS Region:us-east-2:inline>
+# <secrets-destination-path:Secrets Destination Path - relative to devops repo eg. secrets/server or run-script. Leave null for script level:null:inline>
 # <devops-repo:Devops Repo - (just the repo name) eg devops:null:inline:conditional=USING_DEVOPS_REPO>
 # <install-scripts-path:Install Scripts Path - relative to the repo eg. provisioning/server-myserver:null:inline:conditional=USING_DEVOPS_REPO>
 # <github-user:Github User:null:inline:conditional=USING_DEVOPS_REPO>
@@ -37,6 +35,10 @@ USING_DEVOPS_REPO=<using-devops-repo>
 CUSTOM_SCRIPTS_PATH="/root/<devops-repo>/<install-scripts-path>"
 DEVOPS_DESTINATION="/root"
 DEVOPS_REPOSITORY_URL="git@github.com-<devops-repo>:<github-user>/<devops-repo>.git"
+SECRETS_DESTINATION_PATH='<secrets-destination-path>'
+
+# AWS VARS
+AWS_REGION="<aws-region>"
 
 #SHARED VARS
 PHP_VERSION='<php-version>'
@@ -45,10 +47,56 @@ OWNER_USER='<owner-user>'
 DAEMON_USER="<daemon-user>"
 DAEMON_GROUP="<daemon-group>"
 SCRIPT_USER='<script-user>'
-SSH_KEY_PUBLIC="<ssh-public-key>"
-SSH_KEY_PRIVATE="<ssh-private-key>"
-DEVOPS_DEPLOY_KEY_PUBLIC="<devops-public-key>"
-DEVOPS_DEPLOY_KEY_PRIVATE="<devops-private-key>"
+
+# SET FUNCS
+get_secret_value() {
+  local secret_name=$1
+  local secret_prefix=$2
+  local secret_path=$3
+  local secret_echo=$4
+  local secret_file="$secret_path/$secret_name"
+
+  if [ -f "$secret_file" ]; then
+    # If the file exists, read the secret from the file
+    
+    # if secret_echo is true, then cat the file
+    if [ "$secret_echo" = true ]; then
+      # return the value - but it will prob show up on the console/logs
+      cat "$secret_file"
+    fi
+
+    # printf that we found the file locally, and to remove it if you want to get the secret from AWS Secrets Manager
+    printf "============ Found $secret_file - Remove it if you want a fresh version from AWS Secrets Manager\n"
+  else
+    # If the file doesn't exist, retrieve the secret from AWS Secrets Manager
+    local secrets_command="aws secretsmanager get-secret-value --secret-id $secret_prefix/$secret_name --region $AWS_REGION --query SecretString --output text"
+    local secret_value=$($secrets_command)
+
+    # if secrets_path is not empty: 
+    # Save the secret value to the file for future use
+    if [ ! -z "$secret_path" ]; then
+      # if secrets path does not exist, create it
+      mkdir -p "$secret_path"
+      echo "$secret_value" > "$secret_file"
+    fi
+
+    # if secret_echo is true, then echo the value
+    if [ "$secret_echo" = true ]; then
+      # return the value - but it will prob show up on the console/logs
+      echo "$secret_value"
+    fi
+  fi
+}
+
+# ENV VARS or FILE VARS
+# if USING_DEVOPS_REPO is true, then get these values, otherwise set to null
+if [ "$USING_DEVOPS_REPO" = true ]; then
+  DEVOPS_DEPLOY_KEY_PUBLIC=$(get_secret_value "<devops-repo>-deploy-key-pub" "shared" "$DEVOPS_DESTINATION" true)
+  DEVOPS_DEPLOY_KEY_PRIVATE=$(get_secret_value "<devops-repo>-deploy-key" "shared" "$DEVOPS_DESTINATION" true)
+else
+  DEVOPS_DEPLOY_KEY_PUBLIC="null"
+  DEVOPS_DEPLOY_KEY_PRIVATE="null"
+fi
 
 # Script Vars
 DEVOPS_NEW_KEYS=false
@@ -67,26 +115,13 @@ exec 2> >(tee -a $LOG_LOCATION >&2)
 
 #### INSERT PRE-RUN SCRIPT HERE
 
-# Setup the ssh keys for a user on this server
-printf "============ Setup ssh keys\n"
-echo "$SSH_KEY_PUBLIC" > ~/.ssh/id_rsa.pub
-echo "$SSH_KEY_PRIVATE" >> ~/.ssh/id_rsa
-
-# Test the ssh private key
-printf "============ Test SSH Key\n"
-cat ~/.ssh/id_rsa.pub
-
-# Fix Permissions on ssh keys
-printf "============ Fix permissions on ssh keys\n"
-chmod u=rw,go= ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
-
 # Add Github to known hosts
 printf "============ Add github known hosts\n"
 ssh-keyscan github.com >> ~/.ssh/known_hosts
 
 # Add ssh config file to ensure this host uses the correct key
-printf "============ Add ssh config file to ensure this host uses the correct ssh key\n"
-echo -e "\nHost github.com\n\tIdentityFile ~/.ssh/id_rsa\n\tIdentitiesOnly yes" >> ~/.ssh/config
+printf "============ Add ssh config file\n"
+touch ~/.ssh/config
 
 # Setup the deploy keys for devops repo
 if [ "$USING_DEVOPS_REPO" = true ]; then
@@ -127,7 +162,6 @@ if [ "$USING_DEVOPS_REPO" = true ]; then
   printf "============ Add to ssh config file to ensure this host uses the correct key for devops repo\n"
   echo -e "\nHost github.com-<devops-repo>\n\tHostname github.com\n\tIdentityFile=~/.ssh/<devops-repo>_deploy_key\n\tIdentitiesOnly=yes" >> ~/.ssh/config
 fi
-
 
 # Setup $OWNER_USER with the same ssh keys
 printf "============ Setup $OWNER_USER with the same ssh keys\n"
@@ -186,6 +220,82 @@ if [ "$USING_DEVOPS_REPO" = true ]; then
 else
   # need to change custom scripts path to $RUNNING_FROM assuming we are running from /server-<server-name>
   CUSTOM_SCRIPTS_PATH="$RUNNING_FROM"
+fi
+
+# Look for secrets.json to use with AWS secrets manager
+printf "============ Look for secrets.json to use with AWS secrets manager\n"
+# if we are in SIMPLE_DOCKER and NOT using devops repo, look for secrets.json
+if [ "$SIMPLE_DOCKER" = true ] && [ "$USING_DEVOPS_REPO" = false ]; then
+  # if secrets.json exists, then we will use it
+  if [ -f "/var/www/simple-docker/scripts/server-<server-name>/secrets.json" ]; then
+    printf "============ Found secrets.json in SimpleDocker\n"
+    SECRETS_FILE="/var/www/simple-docker/scripts/server-<server-name>/secrets.json"
+  fi
+elif [ "$USING_DEVOPS_REPO" = true ]; then
+  # find secrets.json anywhere in the devops-repo
+  printf "============ Find secrets.json anywhere in the repo\n"
+  FOUND_SECRETS_FILE=$(find "$DEVOPS_DESTINATION/<devops-repo>" -type f -name secrets.json)
+  # if FOUND_SECRETS_FILE is not empty and exists, then we will set SECRETS_FILE
+  if [ -n "$FOUND_SECRETS_FILE" ] && [ -f "$FOUND_SECRETS_FILE" ]; then
+    printf "============ Found secrets.json in DevOps Repo\n"
+    SECRETS_FILE="$FOUND_SECRETS_FILE"
+  fi
+else 
+  # look for it in the running from
+  printf "============ Look for secrets.json in the script directory\n"
+  FOUND_SECRETS_FILE=$(find "$RUNNING_FROM" -type f -name secrets.json)
+  # if FOUND_SECRETS_FILE is not empty and exists, then we will set SECRETS_FILE
+  if [ -n "$FOUND_SECRETS_FILE" ] && [ -f "$FOUND_SECRETS_FILE" ]; then
+    printf "============ Found secrets.json in the running from\n"
+    SECRETS_FILE="$FOUND_SECRETS_FILE"
+  fi
+fi
+
+# if secrets file is not found and using devops repo - error
+if [ "$USING_DEVOPS_REPO" = true ] && [ -z "$SECRETS_FILE" ]; then
+  printf "============ ERROR: Could not find secrets.json in the devops repo. Exiting now.\n"
+  exit 1
+fi
+
+# Retrieve AWS values from AWS Secrets Manager, if we have a secrets.json file
+if [ -f "$SECRETS_FILE" ]; then
+
+  # if SECRETS_DESTINATION_PATH is null, then we will use the /var/www/simple-docker/scripts/server-dev_community_api as secrets folder
+  if [ "$SECRETS_DESTINATION_PATH" == "null" ]; then
+    SECRETS_DESTINATION_PATH="$RUNNING_FROM"
+  # if using devops repo, combine DEVOPS_DESTINATION / SECRETS_DESTINATION_PATH
+  elif [ "$USING_DEVOPS_REPO" = true ]; then
+    SECRETS_DESTINATION_PATH="$DEVOPS_DESTINATION/<devops-repo>/$SECRETS_DESTINATION_PATH"
+  fi
+
+  # make sure we have yq to help read the yaml
+  printf "============ Make sure we have yq to help read the yaml\n"
+  if ! command -v jq &> /dev/null
+  then
+      printf "============ jq could not be found, installing it\n"
+      # install jq
+      sudo apt-get update
+      sudo apt-get install -y jq
+  fi
+
+  printf "============ Retrieve AWS values from AWS Secrets Managere\n"
+
+  # Read and fetch secrets from secrets.json
+  SERVER_NAME='<server-name>'
+  
+  # Read secrets.json and fetch each secret
+  # Extract values using jq and loop through the array
+  jq -r --arg server "$SERVER_NAME" \
+    '.secrets[$server] | to_entries[] | "\(.key) \(.value[])"' \
+    $SECRETS_FILE | while IFS= read -r entry; do
+      # Extract category and values from the entry string
+      prefix=$(echo "$entry" | awk '{print $1}')
+      key=$(echo "$entry" | awk '{print $2}')
+
+      # use the get_secret_value func
+      printf "============ Get secret value for $prefix/$key and store in $SECRETS_DESTINATION_PATH\n"
+      get_secret_value "$key" "$prefix" "$SECRETS_DESTINATION_PATH"
+  done
 fi
 
 # Now we know we can safely sudo su from ubuntu, or su ubuntu when we need to.
